import{ensureAuth,roomRef,playerRef,set,update,onValue,onDisconnect,remove}from"./firebase.js";
const $=s=>document.querySelector(s);let roomCode="",user=null,unsub=null;
const makeCode=()=>Math.floor(100000+Math.random()*900000).toString();
function saveRoom(){sessionStorage.setItem("leapRoom",roomCode)}
function lobby(code){roomCode=code;saveRoom();$("#roomInfo").classList.remove("hidden");$("#roomInfo").innerHTML=`ROOM CODE <strong>${code}</strong><br><small>このコードを対戦相手に共有してください。</small>`;$("#battleLobby").classList.remove("hidden");$("#startBattle").classList.remove("hidden");watchRoom(code)}
async function create(){user=await ensureAuth();roomCode=makeCode();await set(roomRef(roomCode),{status:"waiting",createdAt:Date.now(),players:{[user.uid]:{name:"PLAYER 1",score:0,combo:0,ready:true,online:true}}});await onDisconnect(playerRef(roomCode,user.uid)).remove();$("#onlineStatus").textContent="接続中 / 対戦相手を待っています";$("#you").textContent="PLAYER 1";lobby(roomCode)}
async function join(){const c=$("#room").value.trim();if(!/^\d{6}$/.test(c)){alert("6桁のROOM CODEを入力してください。");return}user=await ensureAuth();const snap=await import("./firebase.js").then(m=>m.get(roomRef(c)));if(!snap.exists()){alert("そのROOMは見つかりません。");return}const data=snap.val();if(Object.keys(data.players||{}).length>=2){alert("このROOMは満員です。");return}await update(roomRef(c),{status:"ready"});await update(playerRef(c,user.uid),{name:"PLAYER 2",score:0,combo:0,ready:true,online:true});await onDisconnect(playerRef(c,user.uid)).remove();$("#onlineStatus").textContent="接続中 / 対戦相手と同期中";$("#you").textContent="PLAYER 2";lobby(c)}
function watchRoom(c){if(unsub)unsub();unsub=onValue(roomRef(c),snap=>{const d=snap.val()||{},ps=Object.entries(d.players||{});const me=user?.uid,opp=ps.find(([id])=>id!==me)?.[1];$("#opponent").textContent=opp?.name||"待機中";$("#onlineStatus").textContent=opp?"接続済み / 2人":"接続中 / 対戦相手を待っています";if(opp&&d.status==="ready")$("#startBattle").classList.remove("hidden")})}
$("#create").onclick=()=>create().catch(e=>alert("Firebase接続エラー: "+e.message));$("#join").onclick=()=>join().catch(e=>alert("Firebase接続エラー: "+e.message));$("#startBattle").onclick=async()=>{await update(roomRef(roomCode),{status:"playing",startedAt:Date.now()});location.href=`game.html?mode=mix&online=1&room=${roomCode}`};
